#!/bin/bash
set -e

blue=$(tput setaf 4)
normal=$(tput sgr0)

display_center(){
    longest=$(cat $1 | awk '{ print length }' | sort -n | tail -1)
    indent=$(( ($(tput cols) - longest) / 2))
    while IFS= read -r line; do
        line_c="$2 $line"
        printf "%${indent}s%s\n" '' "$line_c"
    printf "%s" "$(tput sgr0)"
    done < "$1"
}

type_err(){
    indent=$(( ($(tput cols) / 2) - 15 ))
    printf "%${indent}s%s[ " '' " "
    while read line
    do
        strlen=${#line}
        i=0
        # split single characters into lines
        grep -o . <<<$line | while read a
        do
            # short random delay between keystrokes
            sleep 0.$((RANDOM%3))
            # make fake typo every 30th keystroke
            if [[ $((RANDOM%30)) == 1 ]]
            then
                # print random character between a-z
                printf "\\$(printf %o "$((RANDOM%26+97))")"
                # wait a bit and delete it again
                sleep 0.5; echo -ne '\b'; sleep 0.2
            fi
            # output a space, or $a if it is not null
            echo -n "${a:- }"
            offset=$((strlen - i))
            echo -e -n "\033[s\033[${offset}C${blue}(▲)${normal} ]\033[u"
            i=$((i+1))
        done
        echo -e -n "\033[2C"
        sleep 1
        echo
    done
}

ellipses() {
    indent=$(( ($(tput cols) / 2) - 15))

    declare -a animation=("[  .    ]" "[  ..   ]" "[  ...  ]" "[       ]")

    for (( i=0; i<$1; i++ )); do
        for l in "${animation[@]}"; do
            printf "%${indent}s%s" '' " "
            printf "%s\r" "$l"
            sleep .2
        done
    done
}

echo
echo "brew cask install iterm2" | type_err
sleep 1
echo -e "\r\033[1A\033[K"
echo -e "\033[3A"
display_center "assets/logo_to.txt" ${blue}
sleep 1
ellipses 3
display_center "assets/logo_from.txt" ${normal}
echo
sleep 2

echo "Please enter your github username if you'd like to continue"; read ghub_name
echo "And the email associated with that account?"; read ghub_email
echo "Thanks ${ghub_name}! 😊 Let's get started!"
git config --global user.name ${ghub_name}
git config --global user.email ${ghub_email}

mkdir nmwd_tmp; cd nmwd_tmp

# brew setup
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

brew update
brew upgrade

### desktop utils
brew cask install google-chrome
brew install inkscape
brew install vlc

### productivity
brew install pomotroid

### dev tools
brew cask install iterm2
brew cask install docker

### fonts
brew tap homebrew/cask-fonts
brew install font-hack-nerd-font

### fish
brew install fish
echo "/usr/local/bin/fish" | sudo tee -a /etc/shells
chsh -s `which fish`
curl -L https://get.oh-my.fish | fish

### theming and settings
fish fish_vi_key_bindings
cp ./config/fish_user_key_bindings.fish ~/.config/fish/functions/
fish curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher
fish fisher install IlanCosman/tide

### vim
git clone --depth=1 https://github.com/amix/vimrc.git ~/.vim_runtime
sh ~/.vim_runtime/install_awesome_vimrc.sh
cp config/my_configs.vim ~/.vim_runtime

# couldn't figure out how to install from CLI so do this: https://github.com/tallpants/vscode-theme-iterm2
# iTerm2 > Preferences > Profiles; "Color Presets", "Import"
wget https://raw.githubusercontent.com/tallpants/vscode-theme-iterm2/master/vscode.itermcolors

### VScode
brew cask install visual-studio-code

### other CLI tools
brew install trash
brew install git
brew install gh
brew install wget
brew install npm

### python
brew install anaconda
fish_add_path /usr/local/anaconda3

### code editor
brew cask install visual-studio-code

### science-y things
brew install mactex
wget https://github.com/textext/textext/releases/download/1.3.1/TexText-MacOS-1.3.1.zip
unzip TexText-MacOS-1.3.1.zip
cd TexText-MacOS-1.3.1
python3 setup.py --pdflatex-executable=$(which pdflatex) --skip-requirements-check
cd ..

### chat/communication
brew cask install slack
brew cask install zoomus

### run brew cleanup
brew cleanup

### Set OSX Preferences - borrowed from https://github.com/mathiasbynens/dotfiles/blob/master/.macos

# Close any open System Preferences panes, to prevent them from overriding
# settings we’re about to change
osascript -e 'tell application "System Preferences" to quit'

# System Preferences > Mission Control > do not automatically rearrange Spaces based on most recent use
defaults write com.apple.dock mru-spaces -bool false

# 24-hour clock
defaults write com.apple.menuextra.clock DateFormat -string 'EEE MMM d  H:mm'

# Finder: show all filename extensions
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# disable recents in dock
defaults write com.apple.dock show-recents -bool true

# disable the warning when changing a file extension
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

# disable the “Are you sure you want to open this application?” dialog
defaults write com.apple.LaunchServices LSQuarantine -bool false

# avoid creating .DS_Store files on network or USB volumes
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true

# Trackpad: enable tap to click for this user and for the login screen
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1

# Enable the automatic update check
defaults write com.apple.SoftwareUpdate AutomaticCheckEnabled -bool true

# Download newly available updates in background
defaults write com.apple.SoftwareUpdate AutomaticDownload -int 1

# Install System data files & security updates
defaults write com.apple.SoftwareUpdate CriticalUpdateInstall -int 1

# Don’t display the annoying prompt when quitting iTerm
defaults write com.googlecode.iterm2 PromptOnQuit -bool false

# disable the apple press and hold "feature" for vscode
defaults write com.microsoft.VSCode ApplePressAndHoldEnabled -bool false

# remap §£ to `~
hidutil property --set '{"UserKeyMapping":
    [{"HIDKeyboardModifierMappingSrc":0x700000064,
      "HIDKeyboardModifierMappingDst":0x700000035}]
}'

echo "All done! 🎉 🎉 🎉"
